jobs:
- job: "BreakingChange"
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
  - script: 'scripts/install-dotnet.sh'
    displayName: 'Install .Net'
  - script: 'npm run tsc && node scripts/breaking-change.js'
    displayName: 'Breaking Changes'